### PR TITLE
FIX(Clients) remove system.exit() to output connector stats #60

### LINKED ISSUE #60: Opensource FIX(Clients) aac1 remove system.exit() to output connector stats
https://bitbucket.org/msgqe/dtests/commits/8dbf22aa70c7cb4a15d6f20202c867d0f8518150?at=mt_ha_clean

### PR DESCRIPTION
**Pull request by michalxo**
Fixes #60

### CODE REVIEW

File: jmslib/src/main/java/com/redhat/mqe/lib/ConnectorClient.java [hunk 1]
```diff
@@ -77,7 +77,7 @@ private void startConnections() {
             try {
                 connection.start();
                 connectionsOpened++;
-            } catch (JMSException e) {
+            } catch (JMSException | NullPointerException e) {
```
Comment (jdanekrh) [inline jmslib/src/main/java/com/redhat/mqe/lib/ConnectorClient.java]: Tohle je dost prasarna. Maskuje to NPE kvuli programatorske chybe.

Nahradil bych `System.exit(1);` za `throw new JmsMessagingException(...)` a tady bych ju chytal a strcil bych ji do `exceptions`.

**Comment by michalxo** [comment]
Force-pushed updates to this branch with better handling of connection == null.

**Comment by michalxo** [comment]
Also closes issue 50.
